apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  labels:
    app: nginx-app
data:
  index.html: |
    <html>
    <h1>Selamat Datang</h1>
    </br>
    <h1>Ini adalah aplikasi Nginx sederhana. Ini adalah versi 1 dari Nginx dengan Ingress</h1>
    </html>
