apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configs
data:
  nginx-index: |
    <html><body><h1>Ini tampilan dari NGINX dan nama saya Ramiza Imam Azka Zakaria</h1></body></html>
  httpd-index: |
    <html><body><h1>Ini tampilan dari HTTPD dan nama saya Ramiza Imam Azka Zakaria</h1></body></html>

